spring:
  application:
    name: track
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  security:
    oauth:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key
logging:
  file:
    name: trackula.log
  level:
    org.springframework.security: TRACE
server:
  error:
    include-message: always
    include-binding-errors: always